# Generated by Django 4.2.4 on 2024-05-06 17:55

from django.conf import settings
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Ваш ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=main.models.upload_photo_autor, verbose_name='Фото')),
                ('instagram', models.CharField(blank=True, max_length=50, null=True, verbose_name='Инстаграм')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирован')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Неверный формат поля!', regex='$')], verbose_name='Название')),
                ('price', models.IntegerField(default=0, verbose_name='Цена в рублях')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Мои услуги',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Manicure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='такое время существует', regex='^([1-31].)')], verbose_name='Название')),
                ('time', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Неверный формат времени!', regex='^(([0,1][0-9])|(2[0-2])):(([0-5][0-9])|(00))$')], verbose_name='Время')),
                ('date', models.DateField(default=None, verbose_name='Дата')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('service', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.service', verbose_name='Доступные услуги')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи на ногти',
                'ordering': ['-date', 'title'],
            },
        ),
    ]
