# Generated by Django 4.2.4 on 2024-05-23 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manicure',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='такое время существует', regex='^([1-31].)')], verbose_name='Название'),
        ),
    ]
