# Generated by Django 4.2.4 on 2024-01-15 12:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Неверный формат поля!', regex='$')], verbose_name='Название')),
                ('price', models.IntegerField(default=0, verbose_name='Цена в рублях')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Мои услуги',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Manicure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Неверный формат времени!', regex='^(([0,1][0-9])|(2[0-3])):[0-5][0-9]$')], verbose_name='Время')),
                ('date', models.DateField(default=None, verbose_name='Дата')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('service', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.service', verbose_name='Доступные услуги')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи на ногти',
                'ordering': ['-date', 'time'],
            },
        ),
    ]
