# Generated by Django 4.2.4 on 2024-01-15 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_service_manicure'),
    ]

    operations = [
        migrations.AddField(
            model_name='manicure',
            name='title',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='manicure',
            name='time',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Неверный формат времени!', regex='( ^(([0,1][0-9])|(2[0-2])):[0-9][0-9]$)')], verbose_name='Время'),
        ),
    ]
